-- Execute this script in the Supabase SQL Editor.
-- It creates the tables used by:
-- - /insights/employees
-- - /insights/goals

create extension if not exists pgcrypto;

create table if not exists public.crm_employees (
    id uuid primary key default gen_random_uuid(),
    full_name text not null,
    email text unique,
    role text,
    monthly_goal_value numeric(14, 2) not null default 0,
    monthly_goal_count integer not null default 0,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.crm_goals (
    id uuid primary key default gen_random_uuid(),
    employee_id uuid not null references public.crm_employees(id) on delete cascade,
    goal_month date not null,
    target_value numeric(14, 2) not null default 0,
    target_wins integer not null default 0,
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (employee_id, goal_month)
);

create table if not exists public.cliente_status_history (
    id bigint generated by default as identity primary key,
    cliente_id bigint,
    de_status text,
    para_status text,
    movido_em timestamptz not null default now(),
    movido_por text
);

create or replace function public.crm_set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists crm_employees_set_updated_at on public.crm_employees;
create trigger crm_employees_set_updated_at
before update on public.crm_employees
for each row
execute function public.crm_set_updated_at();

drop trigger if exists crm_goals_set_updated_at on public.crm_goals;
create trigger crm_goals_set_updated_at
before update on public.crm_goals
for each row
execute function public.crm_set_updated_at();

create index if not exists idx_crm_goals_month on public.crm_goals(goal_month);
create index if not exists idx_crm_goals_employee on public.crm_goals(employee_id);
create index if not exists idx_cliente_status_history_movido_em on public.cliente_status_history(movido_em desc);
create index if not exists idx_cliente_status_history_cliente on public.cliente_status_history(cliente_id);

alter table public.crm_employees enable row level security;
alter table public.crm_goals enable row level security;
alter table public.cliente_status_history enable row level security;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'crm_employees'
          and policyname = 'crm_employees_authenticated_all'
    ) then
        create policy crm_employees_authenticated_all
            on public.crm_employees
            for all
            to authenticated
            using (true)
            with check (true);
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'cliente_status_history'
          and policyname = 'cliente_status_history_authenticated_all'
    ) then
        create policy cliente_status_history_authenticated_all
            on public.cliente_status_history
            for all
            to authenticated
            using (true)
            with check (true);
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'crm_goals'
          and policyname = 'crm_goals_authenticated_all'
    ) then
        create policy crm_goals_authenticated_all
            on public.crm_goals
            for all
            to authenticated
            using (true)
            with check (true);
    end if;
end
$$;
