-- =====================================================================
-- CRM POLATTO — MIGRATION 03: LGPD / COMPLIANCE
--
-- Itens da seção 2 do escopo:
--   - Registro de consentimento de coleta de dado pessoal
--   - Direito ao esquecimento (exclusão/anonimização a pedido do titular)
--   - Portabilidade (exportação dos dados do titular)
--   - Política de retenção configurável por tenant
--   - Registro de acesso a dado pessoal (quem acessou o quê)
--
-- IDEMPOTENTE. Executar após 01 e 02.
-- =====================================================================

-- ---------------------------------------------------------------------
-- CONSENTIMENTOS
-- ---------------------------------------------------------------------
create table if not exists public.consentimentos (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid,
    pessoa_id uuid references public.pessoas(id) on delete cascade,
    tipo text not null default 'coleta_dados',      -- coleta_dados | comunicacao_marketing | compartilhamento
    base_legal text not null default 'consentimento', -- consentimento | execucao_contrato | legitimo_interesse
    origem text,                                     -- formulário, importação CSV, integração, verbal etc.
    concedido_em timestamptz not null default now(),
    revogado_em timestamptz,
    detalhes jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

alter table public.consentimentos add column if not exists tenant_id uuid;
alter table public.consentimentos enable row level security;
drop policy if exists consentimentos_tenant_isolation on public.consentimentos;
create policy consentimentos_tenant_isolation on public.consentimentos
    for all to authenticated
    using (public.tenant_filter(tenant_id))
    with check (public.tenant_filter(tenant_id));

drop trigger if exists set_tenant_id on public.consentimentos;
create trigger set_tenant_id before insert on public.consentimentos
for each row execute function public.fn_set_tenant_id();

-- ---------------------------------------------------------------------
-- REGISTRO DE ACESSO A DADO PESSOAL (exigível em incidente de segurança)
-- O frontend chama: select public.log_acesso_titular('<pessoa_id>', 'visualizou detalhe');
-- ---------------------------------------------------------------------
create table if not exists public.acessos_dados_pessoais (
    id bigint generated by default as identity primary key,
    tenant_id uuid,
    pessoa_id uuid,
    acessado_por uuid,          -- auth.uid()
    email_acessor text,
    contexto text,
    criado_em timestamptz not null default now()
);

alter table public.acessos_dados_pessoais enable row level security;
drop policy if exists acessos_dados_pessoais_leitura_admin on public.acessos_dados_pessoais;
create policy acessos_dados_pessoais_leitura_admin on public.acessos_dados_pessoais
    for select to authenticated
    using (public.is_system_admin() or public.tenant_filter(tenant_id));
-- Escrita apenas via função security definer (sem policy de insert).

create or replace function public.log_acesso_titular(p_pessoa_id uuid, p_contexto text default 'visualizacao')
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.acessos_dados_pessoais (tenant_id, pessoa_id, acessado_por, email_acessor, contexto)
    values (
        public.current_tenant_id(),
        p_pessoa_id,
        auth.uid(),
        coalesce(auth.jwt() ->> 'email', 'desconhecido'),
        left(coalesce(p_contexto, 'visualizacao'), 200)
    );
exception when others then
    -- Log de acesso nunca pode derrubar a operação principal
    null;
end;
$$;

-- ---------------------------------------------------------------------
-- PORTABILIDADE: exportação completa dos dados do titular (JSON)
-- Restrita a usuários do próprio tenant; o acesso fica registrado.
-- Uso: select public.lgpd_exportar_dados_titular('<pessoa_id>');
-- ---------------------------------------------------------------------
create or replace function public.lgpd_exportar_dados_titular(p_pessoa_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_tenant uuid;
    v_resultado jsonb;
begin
    select tenant_id into v_tenant from public.pessoas where id = p_pessoa_id;

    if v_tenant is null or not public.tenant_filter(v_tenant) then
        raise exception 'Pessoa não encontrada ou fora do seu tenant.';
    end if;

    perform public.enforce_rate_limit('lgpd_exportar_dados_titular', 30, interval '1 hour');
    perform public.log_acesso_titular(p_pessoa_id, 'exportacao_lgpd');

    select jsonb_build_object(
        'gerado_em', now(),
        'pessoa', to_jsonb(p) - 'tenant_id',
        'organizacao', (select to_jsonb(o) - 'tenant_id' from public.organizacoes o where o.id = p.organizacao_id),
        'negocios', coalesce((
            select jsonb_agg(to_jsonb(n) - 'tenant_id')
            from public.negocios n
            where n.pessoa_contato_principal_id = p.id
               or exists (select 1 from public.negocios_pessoas np where np.pessoa_id = p.id and np.negocio_id = n.id)
        ), '[]'::jsonb),
        'consentimentos', coalesce((
            select jsonb_agg(to_jsonb(c) - 'tenant_id')
            from public.consentimentos c where c.pessoa_id = p.id
        ), '[]'::jsonb)
    )
    into v_resultado
    from public.pessoas p
    where p.id = p_pessoa_id;

    return v_resultado;
end;
$$;

-- ---------------------------------------------------------------------
-- DIREITO AO ESQUECIMENTO: anonimização do titular.
-- Mantém o histórico transacional (negócios, valores, datas) sem dado
-- pessoal identificável. Retorna os paths de Storage que a aplicação
-- deve excluir (SQL não apaga objetos do Storage).
-- Uso: select * from public.lgpd_apagar_dados_titular('<pessoa_id>');
-- ---------------------------------------------------------------------
create or replace function public.lgpd_apagar_dados_titular(p_pessoa_id uuid)
returns table(resultado text, storage_paths_para_excluir text[])
language plpgsql
security definer
set search_path = public
as $$
declare
    v_tenant uuid;
    v_paths text[];
begin
    select tenant_id into v_tenant from public.pessoas where id = p_pessoa_id;

    if v_tenant is null or not public.tenant_filter(v_tenant) then
        raise exception 'Pessoa não encontrada ou fora do seu tenant.';
    end if;

    perform public.enforce_rate_limit('lgpd_apagar_dados_titular', 10, interval '1 hour');
    perform public.log_acesso_titular(p_pessoa_id, 'exclusao_lgpd');

    -- Coleta paths de documentos dos negócios do titular (para exclusão no Storage)
    select coalesce(array_agg(distinct d.caminho_storage), array[]::text[])
    into v_paths
    from public.documentos_lead d
    where d.caminho_storage is not null
      and exists (
          select 1 from public.negocios n
          where n.pessoa_contato_principal_id = p_pessoa_id
            and (d.cliente_id::text = n.id::text or d.cliente_id::text = n.legado_cliente_id)
      );

    -- Anonimiza a pessoa
    update public.pessoas set
        nome = 'Titular removido (LGPD)',
        email = null,
        telefone = null,
        cpf = null,
        cargo = null,
        dados_extras = '{}'::jsonb,
        anonimizada_em = now()
    where id = p_pessoa_id;

    -- O nome do titular é COPIADO para outros lugares no fluxo normal do CRM
    -- (título do negócio, razão social de PF, timeline). Sem limpar aqui, o
    -- "direito ao esquecimento" seria apenas cosmético.
    update public.negocios set titulo = 'Negócio de titular removido (LGPD)'
    where pessoa_contato_principal_id = p_pessoa_id;

    update public.organizacoes o set
        razao_social = 'Organização de titular removido (LGPD)',
        nome_fantasia = null,
        email = null,
        telefone = null
    where exists (
        select 1 from public.pessoas p
        where p.id = p_pessoa_id and p.organizacao_id = o.id
    )
    and not exists (
        -- Só anonimiza a organização se ela não tiver outros contatos ativos
        select 1 from public.pessoas outra
        where outra.organizacao_id = o.id
          and outra.id <> p_pessoa_id
          and outra.anonimizada_em is null
          and outra.deleted_at is null
    );

    -- Timeline e auditoria: remove o conteúdo textual que possa conter dado
    -- pessoal, preservando o registro de que a ação existiu.
    if to_regclass('public.atividades_lead') is not null then
        update public.atividades_lead a set
            titulo = 'Registro anonimizado (LGPD)',
            descricao = null
        where exists (
            select 1 from public.negocios n
            where n.pessoa_contato_principal_id = p_pessoa_id
              and (a.cliente_id = n.id::text or a.cliente_id = n.legado_cliente_id)
        );
    end if;

    update public.audit_log set
        dados_antes = jsonb_build_object('anonimizado', true),
        dados_depois = jsonb_build_object('anonimizado', true)
    where tabela = 'pessoas' and registro_id = p_pessoa_id::text;

    -- Revoga consentimentos
    update public.consentimentos set revogado_em = coalesce(revogado_em, now())
    where pessoa_id = p_pessoa_id;

    resultado := 'Titular anonimizado. Excluir no Storage os paths retornados e revisar anotações manuais em atividades.';
    storage_paths_para_excluir := v_paths;
    return next;
end;
$$;

-- ---------------------------------------------------------------------
-- POLÍTICA DE RETENÇÃO configurável por tenant
-- Ex.: reter negócio perdido por 730 dias; depois soft-delete + anonimizar
-- pessoas sem nenhum negócio ativo.
-- Agendar via Supabase (extensão pg_cron) ou rodar manualmente:
--   select * from public.aplicar_politica_retencao();
-- ---------------------------------------------------------------------
create table if not exists public.politicas_retencao (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid not null,
    entidade text not null default 'negocio_perdido',   -- negocio_perdido | negocio_inativo
    dias_retencao integer not null default 730,
    ativo boolean not null default true,
    created_at timestamptz not null default now(),
    unique (tenant_id, entidade)
);

alter table public.politicas_retencao enable row level security;
drop policy if exists politicas_retencao_tenant_isolation on public.politicas_retencao;
create policy politicas_retencao_tenant_isolation on public.politicas_retencao
    for all to authenticated
    using (public.tenant_filter(tenant_id))
    with check (public.tenant_filter(tenant_id));

create or replace function public.aplicar_politica_retencao()
returns table(tenant uuid, entidade text, registros_afetados bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
    v_politica record;
    v_count bigint;
begin
    -- Esta função é SECURITY DEFINER e apaga dados de TODOS os tenants.
    -- Sem esta guarda qualquer usuário autenticado conseguiria executá-la.
    -- Uso previsto: superadmin ou job agendado (service_role, sem auth.uid).
    if auth.uid() is not null and not public.is_system_admin() then
        raise exception 'Apenas superadmin ou rotina agendada pode aplicar a política de retenção.'
            using errcode = '42501';
    end if;

    for v_politica in
        select * from public.politicas_retencao where ativo
    loop
        if v_politica.entidade = 'negocio_perdido' then
            update public.negocios n
            set deleted_at = now()
            where n.tenant_id = v_politica.tenant_id
              and n.deleted_at is null
              and n.fechado_em is not null
              and n.fechado_em < now() - make_interval(days => v_politica.dias_retencao)
              and exists (
                  select 1 from public.pipeline_stages ps
                  where ps.id = n.stage_id and ps.perdido
              );
        elsif v_politica.entidade = 'negocio_inativo' then
            update public.negocios n
            set deleted_at = now()
            where n.tenant_id = v_politica.tenant_id
              and n.deleted_at is null
              and n.updated_at < now() - make_interval(days => v_politica.dias_retencao);
        else
            continue;  -- entidade desconhecida: não reporta contagem de outra iteração
        end if;

        get diagnostics v_count = row_count;
        tenant := v_politica.tenant_id;
        entidade := v_politica.entidade;
        registros_afetados := v_count;
        return next;
    end loop;

    -- Anonimiza pessoas cujo único vínculo eram negócios já expurgados.
    -- O prazo de retenção também vale aqui: um contato recém-cadastrado que
    -- ainda não tem negócio NÃO pode ser destruído no primeiro ciclo.
    update public.pessoas p
    set nome = 'Titular removido (retenção)',
        email = null, telefone = null, cpf = null, cargo = null,
        dados_extras = '{}'::jsonb,
        anonimizada_em = now()
    from public.politicas_retencao pr
    where p.anonimizada_em is null
      and p.deleted_at is null
      and pr.tenant_id = p.tenant_id
      and pr.ativo
      and p.created_at < now() - make_interval(days => pr.dias_retencao)
      and not exists (
          select 1 from public.negocios n
          where n.deleted_at is null
            and (n.pessoa_contato_principal_id = p.id
                 or exists (select 1 from public.negocios_pessoas np where np.pessoa_id = p.id and np.negocio_id = n.id))
      );
end;
$$;
