-- =====================================================================
-- CRM POLATTO — MIGRATION 04: AUDIT LOG + SOFT DELETE
--
--   - audit_log genérico com trigger automática (INSERT/UPDATE/DELETE)
--     nas tabelas críticas — cobre "quem alterou o quê e quando"
--   - Soft delete nas tabelas principais + função de restauração
--
-- IDEMPOTENTE. Executar após 01 e 02.
-- =====================================================================

-- ---------------------------------------------------------------------
-- AUDIT LOG
-- ---------------------------------------------------------------------
create table if not exists public.audit_log (
    id bigint generated by default as identity primary key,
    tenant_id uuid,
    tabela text not null,
    registro_id text,
    operacao text not null,          -- INSERT | UPDATE | DELETE
    executado_por uuid,              -- auth.uid()
    email_executor text,
    dados_antes jsonb,
    dados_depois jsonb,
    criado_em timestamptz not null default now()
);

create index if not exists idx_audit_log_tabela_registro on public.audit_log (tabela, registro_id);
create index if not exists idx_audit_log_tenant_data on public.audit_log (tenant_id, criado_em desc);

alter table public.audit_log enable row level security;
drop policy if exists audit_log_leitura_tenant on public.audit_log;
create policy audit_log_leitura_tenant on public.audit_log
    for select to authenticated
    using (public.is_system_admin() or public.tenant_filter(tenant_id));
-- Escrita apenas via trigger (security definer). Sem policy de insert/update/delete.

create or replace function public.fn_audit_trigger()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    v_antes jsonb;
    v_depois jsonb;
    v_registro_id text;
    v_tenant uuid;
begin
    if tg_op = 'DELETE' then
        v_antes := to_jsonb(old);
        v_depois := null;
        v_registro_id := old.id::text;
    elsif tg_op = 'UPDATE' then
        v_antes := to_jsonb(old);
        v_depois := to_jsonb(new);
        v_registro_id := new.id::text;
        -- Não loga updates sem mudança real
        if v_antes = v_depois then
            return new;
        end if;
    else
        v_antes := null;
        v_depois := to_jsonb(new);
        v_registro_id := new.id::text;
    end if;

    v_tenant := coalesce(
        nullif(coalesce(v_depois ->> 'tenant_id', v_antes ->> 'tenant_id'), '')::uuid,
        public.current_tenant_id()
    );

    insert into public.audit_log (tenant_id, tabela, registro_id, operacao, executado_por, email_executor, dados_antes, dados_depois)
    values (
        v_tenant,
        tg_table_name,
        v_registro_id,
        tg_op,
        auth.uid(),
        coalesce(auth.jwt() ->> 'email', 'sistema'),
        v_antes,
        v_depois
    );

    if tg_op = 'DELETE' then
        return old;
    end if;
    return new;
exception when others then
    -- Auditoria nunca pode derrubar a operação de negócio
    if tg_op = 'DELETE' then
        return old;
    end if;
    return new;
end;
$$;

do $$
declare
    v_tabela text;
begin
    foreach v_tabela in array array[
        'negocios', 'organizacoes', 'pessoas', 'funcionarios',
        'pipeline_stages', 'pipelines', 'custom_fields',
        'motivos_perda', 'tipos_atividade', 'documentos_lead', 'metas'
    ] loop
        if to_regclass('public.' || v_tabela) is not null then
            execute format('drop trigger if exists audit_changes on public.%I', v_tabela);
            execute format(
                'create trigger audit_changes after insert or update or delete on public.%I for each row execute function public.fn_audit_trigger()',
                v_tabela
            );
        end if;
    end loop;
end $$;

-- ---------------------------------------------------------------------
-- TIMELINE AUTOMÁTICA: mudança de etapa do negócio registrada por trigger
-- (substitui a dependência de o frontend lembrar de chamar addLeadActivity)
-- ---------------------------------------------------------------------
create or replace function public.fn_registrar_mudanca_stage()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    v_de text;
    v_para text;
begin
    if old.stage_id is distinct from new.stage_id or old.status is distinct from new.status then
        select nome into v_de from public.pipeline_stages where id = old.stage_id;
        select nome into v_para from public.pipeline_stages where id = new.stage_id;

        if to_regclass('public.cliente_status_history') is not null then
            insert into public.cliente_status_history (cliente_id, de_status, para_status, movido_por)
            values (
                nullif(regexp_replace(coalesce(new.legado_cliente_id, ''), '\D', '', 'g'), '')::bigint,
                coalesce(v_de, old.status),
                coalesce(v_para, new.status),
                coalesce(auth.jwt() ->> 'email', 'sistema')
            );
        end if;

        if to_regclass('public.atividades_lead') is not null then
            insert into public.atividades_lead (cliente_id, tenant_id, activity_type, titulo, de_status, para_status, criado_por, data_atividade)
            values (
                new.id::text,
                new.tenant_id,
                'status',
                format('Etapa alterada: %s -> %s', coalesce(v_de, old.status, '?'), coalesce(v_para, new.status, '?')),
                coalesce(v_de, old.status),
                coalesce(v_para, new.status),
                coalesce(auth.jwt() ->> 'email', 'sistema'),
                now()
            );
        end if;
    end if;

    return new;
exception when others then
    return new;
end;
$$;

drop trigger if exists registrar_mudanca_stage on public.negocios;
create trigger registrar_mudanca_stage
after update on public.negocios
for each row execute function public.fn_registrar_mudanca_stage();

-- ---------------------------------------------------------------------
-- SOFT DELETE nas tabelas principais (colunas já criadas no arquivo 01
-- para o modelo novo; aqui cobre as legadas) + restauração
-- ---------------------------------------------------------------------
alter table if exists public.tarefas add column if not exists deleted_at timestamptz;
alter table if exists public.funcionarios add column if not exists deleted_at timestamptz;
alter table if exists public.documentos_lead add column if not exists deleted_at timestamptz;

create or replace function public.restaurar_registro(p_tabela text, p_id text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
    v_permitidas text[] := array['negocios', 'pessoas', 'organizacoes', 'tarefas', 'funcionarios', 'documentos_lead'];
begin
    if not (p_tabela = any(v_permitidas)) then
        raise exception 'Tabela % não suporta restauração.', p_tabela;
    end if;

    execute format(
        'update public.%I set deleted_at = null where id::text = $1 and public.tenant_filter(tenant_id)',
        p_tabela
    ) using p_id;

    return found;
end;
$$;

comment on function public.restaurar_registro(text, text) is 'Desfaz soft delete de um registro do próprio tenant. Ex.: select restaurar_registro(''negocios'', ''<uuid>'');';
