-- =====================================================================
-- CRM POLATTO — MIGRATION 04: AUDIT LOG + SOFT DELETE
--
--   - audit_log genérico com trigger automática (INSERT/UPDATE/DELETE)
--     nas tabelas críticas — cobre "quem alterou o quê e quando"
--   - Soft delete nas tabelas principais + função de restauração
--
-- IDEMPOTENTE. Executar após 01 e 02.
-- =====================================================================

-- ---------------------------------------------------------------------
-- AUDIT LOG
-- ---------------------------------------------------------------------
create table if not exists public.audit_log (
    id bigint generated by default as identity primary key,
    tenant_id uuid,
    tabela text not null,
    registro_id text,
    operacao text not null,          -- INSERT | UPDATE | DELETE
    executado_por uuid,              -- auth.uid()
    email_executor text,
    dados_antes jsonb,
    dados_depois jsonb,
    criado_em timestamptz not null default now()
);

create index if not exists idx_audit_log_tabela_registro on public.audit_log (tabela, registro_id);
create index if not exists idx_audit_log_tenant_data on public.audit_log (tenant_id, criado_em desc);

alter table public.audit_log enable row level security;
drop policy if exists audit_log_leitura_tenant on public.audit_log;
create policy audit_log_leitura_tenant on public.audit_log
    for select to authenticated
    using (public.is_system_admin() or public.tenant_filter(tenant_id));
-- Escrita apenas via trigger (security definer). Sem policy de insert/update/delete.

create or replace function public.fn_audit_trigger()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    v_antes jsonb;
    v_depois jsonb;
    v_registro_id text;
    v_tenant uuid;
begin
    if tg_op = 'DELETE' then
        v_antes := to_jsonb(old);
        v_depois := null;
        v_registro_id := old.id::text;
    elsif tg_op = 'UPDATE' then
        v_antes := to_jsonb(old);
        v_depois := to_jsonb(new);
        v_registro_id := new.id::text;
        -- Não loga updates sem mudança real
        if v_antes = v_depois then
            return new;
        end if;
    else
        v_antes := null;
        v_depois := to_jsonb(new);
        v_registro_id := new.id::text;
    end if;

    v_tenant := coalesce(
        nullif(coalesce(v_depois ->> 'tenant_id', v_antes ->> 'tenant_id'), '')::uuid,
        public.current_tenant_id()
    );

    insert into public.audit_log (tenant_id, tabela, registro_id, operacao, executado_por, email_executor, dados_antes, dados_depois)
    values (
        v_tenant,
        tg_table_name,
        v_registro_id,
        tg_op,
        auth.uid(),
        coalesce(auth.jwt() ->> 'email', 'sistema'),
        v_antes,
        v_depois
    );

    if tg_op = 'DELETE' then
        return old;
    end if;
    return new;
exception when others then
    -- Auditoria nunca pode derrubar a operação de negócio
    if tg_op = 'DELETE' then
        return old;
    end if;
    return new;
end;
$$;

do $$
declare
    v_tabela text;
begin
    foreach v_tabela in array array[
        'negocios', 'organizacoes', 'pessoas', 'funcionarios',
        'pipeline_stages', 'pipelines', 'custom_fields',
        'motivos_perda', 'tipos_atividade', 'documentos_lead', 'metas'
    ] loop
        if to_regclass('public.' || v_tabela) is not null then
            execute format('drop trigger if exists audit_changes on public.%I', v_tabela);
            execute format(
                'create trigger audit_changes after insert or update or delete on public.%I for each row execute function public.fn_audit_trigger()',
                v_tabela
            );
        end if;
    end loop;
end $$;

-- ---------------------------------------------------------------------
-- TIMELINE AUTOMÁTICA: mudança de etapa do negócio registrada por trigger
-- (substitui a dependência de o frontend lembrar de chamar addLeadActivity)
-- ---------------------------------------------------------------------
-- Helper: a tabela tem essa coluna? (atividades_lead acumulou variações de
-- schema ao longo do tempo — tipo/activity_type, titulo/title, criado_por/author)
create or replace function public.tem_coluna(p_tabela text, p_coluna text)
returns boolean
language sql
stable
as $$
    select exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = p_tabela and column_name = p_coluna
    );
$$;

create or replace function public.fn_registrar_mudanca_stage()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    v_de text;
    v_para text;
    v_titulo text;
    v_autor text;
    v_payload jsonb;
    v_cols text;
    v_vals text;
begin
    if old.stage_id is not distinct from new.stage_id
       and old.status is not distinct from new.status then
        return new;
    end if;

    select nome into v_de from public.pipeline_stages where id = old.stage_id;
    select nome into v_para from public.pipeline_stages where id = new.stage_id;

    v_de := coalesce(v_de, old.status);
    v_para := coalesce(v_para, new.status);
    v_titulo := format('Etapa alterada: %s -> %s', coalesce(v_de, '?'), coalesce(v_para, '?'));
    v_autor := coalesce(auth.jwt() ->> 'email', 'sistema');

    if to_regclass('public.cliente_status_history') is not null then
        insert into public.cliente_status_history (cliente_id, de_status, para_status, movido_por)
        values (
            nullif(regexp_replace(coalesce(new.legado_cliente_id, ''), '\D', '', 'g'), '')::bigint,
            v_de, v_para, v_autor
        );
    end if;

    -- Monta o insert apenas com as colunas que a tabela realmente tem.
    -- Um insert de colunas fixas falharia silencioso e a timeline
    -- automática nunca funcionaria.
    if to_regclass('public.atividades_lead') is not null then
        v_payload := jsonb_strip_nulls(jsonb_build_object(
            'cliente_id',    new.id::text,
            'tenant_id',     new.tenant_id::text,
            'activity_type', 'status',
            'tipo',          'status',
            'titulo',        v_titulo,
            'title',         v_titulo,
            'descricao',     v_titulo,
            'de_status',     v_de,
            'from_status',   v_de,
            'para_status',   v_para,
            'to_status',     v_para,
            'criado_por',    v_autor,
            'author',        v_autor
        ));

        select string_agg(quote_ident(k), ', '), string_agg(quote_literal(v), ', ')
        into v_cols, v_vals
        from jsonb_each_text(v_payload) as e(k, v)
        where public.tem_coluna('atividades_lead', k);

        if v_cols is not null then
            if public.tem_coluna('atividades_lead', 'data_atividade') then
                v_cols := v_cols || ', data_atividade';
                v_vals := v_vals || ', now()';
            end if;
            execute format('insert into public.atividades_lead (%s) values (%s)', v_cols, v_vals);
        end if;
    end if;

    return new;
exception when others then
    -- A timeline nunca pode impedir a movimentação de um negócio
    return new;
end;
$$;

drop trigger if exists registrar_mudanca_stage on public.negocios;
create trigger registrar_mudanca_stage
after update on public.negocios
for each row execute function public.fn_registrar_mudanca_stage();

-- ---------------------------------------------------------------------
-- SOFT DELETE nas tabelas principais (colunas já criadas no arquivo 01
-- para o modelo novo; aqui cobre as legadas) + restauração
-- ---------------------------------------------------------------------
alter table if exists public.tarefas add column if not exists deleted_at timestamptz;
alter table if exists public.funcionarios add column if not exists deleted_at timestamptz;
alter table if exists public.documentos_lead add column if not exists deleted_at timestamptz;

create or replace function public.restaurar_registro(p_tabela text, p_id text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
    v_permitidas text[] := array['negocios', 'pessoas', 'organizacoes', 'tarefas', 'funcionarios', 'documentos_lead'];
    v_afetados integer;
begin
    if not (p_tabela = any(v_permitidas)) then
        raise exception 'Tabela % não suporta restauração.', p_tabela;
    end if;

    execute format(
        'update public.%I set deleted_at = null where id::text = $1 and public.tenant_filter(tenant_id)',
        p_tabela
    ) using p_id;

    -- FOUND não é atualizado por EXECUTE em PL/pgSQL: sem GET DIAGNOSTICS
    -- esta função retornava false mesmo quando a restauração funcionava.
    get diagnostics v_afetados = row_count;
    return v_afetados > 0;
end;
$$;

comment on function public.restaurar_registro(text, text) is 'Desfaz soft delete de um registro do próprio tenant. Ex.: select restaurar_registro(''negocios'', ''<uuid>'');';
