-- =====================================================================
-- CRM POLATTO — MIGRATION 01: MODELO RELACIONAL CANÔNICO
-- organizacoes → pessoas → negocios (estilo Pipedrive)
-- + pipelines múltiplos, custom fields, motivos de perda, tipos de atividade
--
-- IDEMPOTENTE: pode rodar várias vezes. Alinha o banco com este arquivo
-- sem destruir dados nem colunas já existentes em produção.
-- ORDEM: executar os arquivos desta pasta em ordem numérica (01..07).
-- =====================================================================

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------
-- Stub de current_tenant_id() — a implementação real (fail-closed, lida
-- do vínculo do usuário autenticado) é criada no arquivo 02. Este stub
-- só existe para as funções deste arquivo compilarem se 02 ainda não rodou.
-- ---------------------------------------------------------------------
do $$
begin
    if not exists (
        select 1 from pg_proc p join pg_namespace ns on ns.oid = p.pronamespace
        where ns.nspname = 'public' and p.proname = 'current_tenant_id'
    ) then
        create function public.current_tenant_id() returns uuid
        language sql stable as 'select null::uuid';
    end if;
end $$;

-- ---------------------------------------------------------------------
-- Conversor numérico seguro: aceita numeric, "1234.56", "1.234,56",
-- "R$ 1.234,56" — retorna null em vez de abortar quando não parseável.
-- Usado na migração de dados e na view de compatibilidade.
-- ---------------------------------------------------------------------
create or replace function public.to_numeric_seguro(p_valor text)
returns numeric
language plpgsql
immutable
as $$
declare
    v text;
begin
    if p_valor is null or trim(p_valor) = '' then
        return null;
    end if;
    v := regexp_replace(p_valor, '[^0-9,.\-]', '', 'g');
    if v = '' then
        return null;
    end if;
    -- Formato brasileiro: última vírgula é decimal ("1.234,56" → "1234.56")
    if position(',' in v) > 0 then
        v := replace(replace(v, '.', ''), ',', '.');
    end if;
    return v::numeric;
exception when others then
    return null;
end;
$$;

-- ---------------------------------------------------------------------
-- Função utilitária de updated_at (compartilhada por todas as tabelas)
-- ---------------------------------------------------------------------
create or replace function public.crm_set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

-- ---------------------------------------------------------------------
-- PIPELINES (múltiplos funis por tenant)
-- ---------------------------------------------------------------------
create table if not exists public.pipelines (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid,
    nome text not null,
    ordem integer not null default 1,
    ativo boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.pipelines add column if not exists tenant_id uuid;
alter table public.pipelines add column if not exists nome text;
alter table public.pipelines add column if not exists ordem integer default 1;
alter table public.pipelines add column if not exists ativo boolean default true;
alter table public.pipelines add column if not exists created_at timestamptz default now();
alter table public.pipelines add column if not exists updated_at timestamptz default now();

drop trigger if exists pipelines_set_updated_at on public.pipelines;
create trigger pipelines_set_updated_at
before update on public.pipelines
for each row execute function public.crm_set_updated_at();

-- ---------------------------------------------------------------------
-- PIPELINE_STAGES — upgrade da tabela existente
-- (ganha tenant_id, pipeline_id e probabilidade para forecast)
-- ---------------------------------------------------------------------
create table if not exists public.pipeline_stages (
    id bigint generated by default as identity primary key,
    nome text,
    cor text,
    ordem integer default 0
);

alter table public.pipeline_stages add column if not exists tenant_id uuid;
alter table public.pipeline_stages add column if not exists pipeline_id uuid;
alter table public.pipeline_stages add column if not exists probabilidade integer default 0;
alter table public.pipeline_stages add column if not exists ganho boolean default false;
alter table public.pipeline_stages add column if not exists perdido boolean default false;

comment on column public.pipeline_stages.probabilidade is 'Percentual (0-100) usado no forecast: valor do negócio × probabilidade da etapa.';
comment on column public.pipeline_stages.ganho is 'Etapa terminal de ganho (equivale ao antigo status "Fechado").';
comment on column public.pipeline_stages.perdido is 'Etapa terminal de perda (equivale ao antigo status "Perdido").';

update public.pipeline_stages set ganho = true
where ganho is distinct from true and (coalesce(nome,'') ilike '%fechado%' or coalesce(nome,'') ilike '%ganho%');

update public.pipeline_stages set perdido = true
where perdido is distinct from true and coalesce(nome,'') ilike '%perdido%';

-- ---------------------------------------------------------------------
-- ORGANIZACOES (Pessoa Jurídica — quem assina contrato / emite NF)
-- ---------------------------------------------------------------------
create table if not exists public.organizacoes (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid,
    razao_social text,
    nome_fantasia text,
    cnpj text,
    site text,
    setor text,
    tamanho text,
    telefone text,
    email text,
    endereco jsonb not null default '{}'::jsonb,
    dados_extras jsonb not null default '{}'::jsonb,
    deleted_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.organizacoes add column if not exists tenant_id uuid;
alter table public.organizacoes add column if not exists razao_social text;
alter table public.organizacoes add column if not exists nome_fantasia text;
alter table public.organizacoes add column if not exists cnpj text;
alter table public.organizacoes add column if not exists site text;
alter table public.organizacoes add column if not exists setor text;
alter table public.organizacoes add column if not exists tamanho text;
alter table public.organizacoes add column if not exists telefone text;
alter table public.organizacoes add column if not exists email text;
alter table public.organizacoes add column if not exists endereco jsonb default '{}'::jsonb;
alter table public.organizacoes add column if not exists dados_extras jsonb default '{}'::jsonb;
alter table public.organizacoes add column if not exists deleted_at timestamptz;
alter table public.organizacoes add column if not exists created_at timestamptz default now();
alter table public.organizacoes add column if not exists updated_at timestamptz default now();

drop trigger if exists organizacoes_set_updated_at on public.organizacoes;
create trigger organizacoes_set_updated_at
before update on public.organizacoes
for each row execute function public.crm_set_updated_at();

-- ---------------------------------------------------------------------
-- PESSOAS (contatos — com quem o vendedor fala)
-- ---------------------------------------------------------------------
create table if not exists public.pessoas (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid,
    organizacao_id uuid,
    nome text,
    email text,
    telefone text,
    ddi text default '+55',
    cpf text,
    cargo text,
    dados_extras jsonb not null default '{}'::jsonb,
    anonimizada_em timestamptz,
    deleted_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.pessoas add column if not exists tenant_id uuid;
alter table public.pessoas add column if not exists organizacao_id uuid;
alter table public.pessoas add column if not exists nome text;
alter table public.pessoas add column if not exists email text;
alter table public.pessoas add column if not exists telefone text;
alter table public.pessoas add column if not exists ddi text default '+55';
alter table public.pessoas add column if not exists cpf text;
alter table public.pessoas add column if not exists cargo text;
alter table public.pessoas add column if not exists dados_extras jsonb default '{}'::jsonb;
alter table public.pessoas add column if not exists anonimizada_em timestamptz;
alter table public.pessoas add column if not exists deleted_at timestamptz;
alter table public.pessoas add column if not exists created_at timestamptz default now();
alter table public.pessoas add column if not exists updated_at timestamptz default now();

comment on column public.pessoas.anonimizada_em is 'Preenchido quando o titular exerce o direito ao esquecimento (LGPD). Dados pessoais foram removidos.';

drop trigger if exists pessoas_set_updated_at on public.pessoas;
create trigger pessoas_set_updated_at
before update on public.pessoas
for each row execute function public.crm_set_updated_at();

-- ---------------------------------------------------------------------
-- MOTIVOS_PERDA (configurável por tenant)
-- ---------------------------------------------------------------------
create table if not exists public.motivos_perda (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid,
    nome text not null,
    ordem integer not null default 1,
    ativo boolean not null default true,
    created_at timestamptz not null default now()
);

alter table public.motivos_perda add column if not exists tenant_id uuid;
alter table public.motivos_perda add column if not exists nome text;
alter table public.motivos_perda add column if not exists ordem integer default 1;
alter table public.motivos_perda add column if not exists ativo boolean default true;
alter table public.motivos_perda add column if not exists created_at timestamptz default now();

-- ---------------------------------------------------------------------
-- TIPOS_ATIVIDADE (configurável por tenant)
-- ---------------------------------------------------------------------
create table if not exists public.tipos_atividade (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid,
    nome text not null,
    icone text,
    ordem integer not null default 1,
    ativo boolean not null default true,
    created_at timestamptz not null default now()
);

alter table public.tipos_atividade add column if not exists tenant_id uuid;
alter table public.tipos_atividade add column if not exists nome text;
alter table public.tipos_atividade add column if not exists icone text;
alter table public.tipos_atividade add column if not exists ordem integer default 1;
alter table public.tipos_atividade add column if not exists ativo boolean default true;
alter table public.tipos_atividade add column if not exists created_at timestamptz default now();

-- ---------------------------------------------------------------------
-- CUSTOM_FIELDS (campos customizados por tenant — armazenamento JSONB)
-- Os valores ficam em dados_extras (jsonb) de negocios/pessoas/organizacoes.
-- Esta tabela guarda apenas a definição (para renderizar o formulário).
-- ---------------------------------------------------------------------
create table if not exists public.custom_fields (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid,
    entidade text not null check (entidade in ('negocio','pessoa','organizacao')),
    chave text not null,
    label text not null,
    tipo text not null default 'texto' check (tipo in ('texto','numero','data','select','boolean')),
    opcoes jsonb not null default '[]'::jsonb,
    ordem integer not null default 1,
    obrigatorio boolean not null default false,
    ativo boolean not null default true,
    created_at timestamptz not null default now()
);

alter table public.custom_fields add column if not exists tenant_id uuid;
alter table public.custom_fields add column if not exists entidade text;
alter table public.custom_fields add column if not exists chave text;
alter table public.custom_fields add column if not exists label text;
alter table public.custom_fields add column if not exists tipo text default 'texto';
alter table public.custom_fields add column if not exists opcoes jsonb default '[]'::jsonb;
alter table public.custom_fields add column if not exists ordem integer default 1;
alter table public.custom_fields add column if not exists obrigatorio boolean default false;
alter table public.custom_fields add column if not exists ativo boolean default true;
alter table public.custom_fields add column if not exists created_at timestamptz default now();

-- ---------------------------------------------------------------------
-- NEGOCIOS (o "deal" — antigo clientes)
-- SEM default de tenant_id: o preenchimento seguro é feito por trigger
-- no arquivo 02 (fn_set_tenant_id). Nunca confiar no frontend.
-- ---------------------------------------------------------------------
create table if not exists public.negocios (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid,
    organizacao_id uuid,
    pessoa_contato_principal_id uuid,
    titulo text,
    valor numeric(14,2),
    stage_id bigint,
    pipeline_id uuid,
    status text,
    temperatura text,
    responsavel text,
    responsavel_id uuid,
    motivo_perda text,
    motivo_perda_id uuid,
    data_prevista_fechamento date,
    fechado_em timestamptz,
    dados_extras jsonb not null default '{}'::jsonb,
    legado_cliente_id text,
    deleted_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.negocios add column if not exists tenant_id uuid;
alter table public.negocios add column if not exists organizacao_id uuid;
alter table public.negocios add column if not exists pessoa_contato_principal_id uuid;
alter table public.negocios add column if not exists titulo text;
alter table public.negocios add column if not exists valor numeric(14,2);
alter table public.negocios add column if not exists stage_id bigint;
alter table public.negocios add column if not exists pipeline_id uuid;
alter table public.negocios add column if not exists status text;
alter table public.negocios add column if not exists temperatura text;
alter table public.negocios add column if not exists responsavel text;
alter table public.negocios add column if not exists responsavel_id uuid;
alter table public.negocios add column if not exists motivo_perda text;
alter table public.negocios add column if not exists motivo_perda_id uuid;
alter table public.negocios add column if not exists data_prevista_fechamento date;
alter table public.negocios add column if not exists fechado_em timestamptz;
alter table public.negocios add column if not exists dados_extras jsonb default '{}'::jsonb;
alter table public.negocios add column if not exists legado_cliente_id text;
alter table public.negocios add column if not exists deleted_at timestamptz;
alter table public.negocios add column if not exists created_at timestamptz default now();
alter table public.negocios add column if not exists updated_at timestamptz default now();

comment on column public.negocios.legado_cliente_id is 'ID original na tabela clientes antes da migração. Garante idempotência da migração de dados.';
comment on column public.negocios.dados_extras is 'Valores dos campos customizados do tenant (definidos em custom_fields) + campos herdados do modelo solar (cep, endereco_instalacao, conta_energia_media, etc).';

drop trigger if exists negocios_set_updated_at on public.negocios;
create trigger negocios_set_updated_at
before update on public.negocios
for each row execute function public.crm_set_updated_at();

-- ---------------------------------------------------------------------
-- NEGOCIOS_PESSOAS (N:N — múltiplos contatos por negócio, com papel)
-- ---------------------------------------------------------------------
create table if not exists public.negocios_pessoas (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid,
    negocio_id uuid not null,
    pessoa_id uuid not null,
    papel text default 'contato',
    created_at timestamptz not null default now(),
    unique (negocio_id, pessoa_id)
);

alter table public.negocios_pessoas add column if not exists tenant_id uuid;
alter table public.negocios_pessoas add column if not exists papel text default 'contato';
alter table public.negocios_pessoas add column if not exists created_at timestamptz default now();

-- ---------------------------------------------------------------------
-- TENANT_FEATURES (feature flags por tenant — ativação gradual sem quebrar UX)
-- ---------------------------------------------------------------------
create table if not exists public.tenant_features (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid not null,
    feature_key text not null,
    enabled boolean not null default false,
    created_at timestamptz not null default now(),
    unique (tenant_id, feature_key)
);

-- ---------------------------------------------------------------------
-- FOREIGN KEYS FORMAIS (NOT VALID: não trava em dado legado; valida depois)
-- Cada uma em bloco isolado: se uma falhar (tipo divergente em produção),
-- as demais continuam e o erro vira NOTICE em vez de abortar o script.
-- ---------------------------------------------------------------------
do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'fk_pipeline_stages_pipeline') then
        alter table public.pipeline_stages
            add constraint fk_pipeline_stages_pipeline
            foreign key (pipeline_id) references public.pipelines(id) on delete set null not valid;
    end if;
exception when others then
    raise notice 'fk_pipeline_stages_pipeline não aplicada: %', sqlerrm;
end $$;

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'fk_pessoas_organizacao') then
        alter table public.pessoas
            add constraint fk_pessoas_organizacao
            foreign key (organizacao_id) references public.organizacoes(id) on delete set null not valid;
    end if;
exception when others then
    raise notice 'fk_pessoas_organizacao não aplicada: %', sqlerrm;
end $$;

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'fk_negocios_organizacao') then
        alter table public.negocios
            add constraint fk_negocios_organizacao
            foreign key (organizacao_id) references public.organizacoes(id) on delete set null not valid;
    end if;
exception when others then
    raise notice 'fk_negocios_organizacao não aplicada: %', sqlerrm;
end $$;

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'fk_negocios_pessoa_principal') then
        alter table public.negocios
            add constraint fk_negocios_pessoa_principal
            foreign key (pessoa_contato_principal_id) references public.pessoas(id) on delete set null not valid;
    end if;
exception when others then
    raise notice 'fk_negocios_pessoa_principal não aplicada: %', sqlerrm;
end $$;

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'fk_negocios_stage') then
        alter table public.negocios
            add constraint fk_negocios_stage
            foreign key (stage_id) references public.pipeline_stages(id) on delete set null not valid;
    end if;
exception when others then
    raise notice 'fk_negocios_stage não aplicada (tipo de stage_id divergente?): %', sqlerrm;
end $$;

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'fk_negocios_pipeline') then
        alter table public.negocios
            add constraint fk_negocios_pipeline
            foreign key (pipeline_id) references public.pipelines(id) on delete set null not valid;
    end if;
exception when others then
    raise notice 'fk_negocios_pipeline não aplicada: %', sqlerrm;
end $$;

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'fk_negocios_responsavel') then
        alter table public.negocios
            add constraint fk_negocios_responsavel
            foreign key (responsavel_id) references public.funcionarios(id) on delete set null not valid;
    end if;
exception when others then
    raise notice 'fk_negocios_responsavel não aplicada: %', sqlerrm;
end $$;

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'fk_negocios_motivo_perda') then
        alter table public.negocios
            add constraint fk_negocios_motivo_perda
            foreign key (motivo_perda_id) references public.motivos_perda(id) on delete set null not valid;
    end if;
exception when others then
    raise notice 'fk_negocios_motivo_perda não aplicada: %', sqlerrm;
end $$;

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'fk_negocios_pessoas_negocio') then
        alter table public.negocios_pessoas
            add constraint fk_negocios_pessoas_negocio
            foreign key (negocio_id) references public.negocios(id) on delete cascade not valid;
    end if;
exception when others then
    raise notice 'fk_negocios_pessoas_negocio não aplicada: %', sqlerrm;
end $$;

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'fk_negocios_pessoas_pessoa') then
        alter table public.negocios_pessoas
            add constraint fk_negocios_pessoas_pessoa
            foreign key (pessoa_id) references public.pessoas(id) on delete cascade not valid;
    end if;
exception when others then
    raise notice 'fk_negocios_pessoas_pessoa não aplicada: %', sqlerrm;
end $$;

-- Tenta validar as FKs criadas como NOT VALID (se houver dado órfão, apenas avisa)
do $$
declare r record;
begin
    for r in
        select conrelid::regclass::text as tabela, conname
        from pg_constraint
        where connamespace = 'public'::regnamespace
          and contype = 'f'
          and not convalidated
          and conname like 'fk_%'
    loop
        begin
            execute format('alter table %s validate constraint %I', r.tabela, r.conname);
        exception when others then
            raise notice 'Constraint % em % contém dado órfão — corrigir e validar depois: %', r.conname, r.tabela, sqlerrm;
        end;
    end loop;
end $$;

-- ---------------------------------------------------------------------
-- SEEDS por tenant (idempotentes): pipeline default + motivos + tipos
-- Executar após criar um tenant: select public.provisionar_defaults_tenant('<tenant_uuid>');
-- ---------------------------------------------------------------------
create or replace function public.provisionar_defaults_tenant(p_tenant_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_pipeline_id uuid;
begin
    -- Pipeline default "Vendas"
    select id into v_pipeline_id
    from public.pipelines
    where tenant_id = p_tenant_id
    order by ordem
    limit 1;

    if v_pipeline_id is null then
        insert into public.pipelines (tenant_id, nome, ordem, ativo)
        values (p_tenant_id, 'Vendas', 1, true)
        returning id into v_pipeline_id;
    end if;

    -- Vincula ao funil default apenas as etapas QUE JÁ SÃO DESTE TENANT.
    -- Incluir tenant_id IS NULL faria o primeiro tenant provisionado
    -- sequestrar as etapas legadas compartilhadas, e os demais tenants
    -- ficariam sem funil. O backfill das órfãs é feito na migration 09.
    update public.pipeline_stages
    set pipeline_id = v_pipeline_id
    where pipeline_id is null
      and tenant_id = p_tenant_id;

    -- Motivos de perda default
    insert into public.motivos_perda (tenant_id, nome, ordem)
    select p_tenant_id, m.nome, m.ordem
    from (values
        ('Preço', 1),
        ('Escolheu concorrente', 2),
        ('Sem orçamento', 3),
        ('Sem resposta / esfriou', 4),
        ('Fora do perfil', 5),
        ('Outro', 6)
    ) as m(nome, ordem)
    where not exists (
        select 1 from public.motivos_perda mp
        where mp.tenant_id = p_tenant_id and mp.nome = m.nome
    );

    -- Tipos de atividade default
    insert into public.tipos_atividade (tenant_id, nome, icone, ordem)
    select p_tenant_id, t.nome, t.icone, t.ordem
    from (values
        ('Ligação', 'phone', 1),
        ('Reunião', 'team', 2),
        ('E-mail', 'mail', 3),
        ('Tarefa', 'check-square', 4),
        ('Visita', 'environment', 5),
        ('Follow-up', 'clock-circle', 6)
    ) as t(nome, icone, ordem)
    where not exists (
        select 1 from public.tipos_atividade ta
        where ta.tenant_id = p_tenant_id and ta.nome = t.nome
    );
end;
$$;

-- ---------------------------------------------------------------------
-- MIGRAÇÃO DE DADOS: clientes (tabela antiga) → organizacoes/pessoas/negocios
-- Idempotente via negocios.legado_cliente_id. Roda apenas se a tabela
-- física clientes ainda existir. Dry-run: select * from public.migrar_clientes_para_negocios(true);
-- ---------------------------------------------------------------------
create or replace function public.migrar_clientes_para_negocios(p_dry_run boolean default true)
returns table(acao text, quantidade bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
    v_row record;
    v_pessoa_id uuid;
    v_org_id uuid;
    v_digits text;
    v_migrados bigint := 0;
    v_pulados bigint := 0;
    v_orgs bigint := 0;
begin
    -- Só roda se clientes for uma TABELA física (não a view de compatibilidade)
    if not exists (
        select 1 from information_schema.tables
        where table_schema = 'public' and table_name = 'clientes' and table_type = 'BASE TABLE'
    ) then
        return query select 'clientes não é tabela física — nada a migrar'::text, 0::bigint;
        return;
    end if;

    for v_row in execute 'select * from public.clientes' loop
        -- idempotência: já migrado?
        if exists (select 1 from public.negocios n where n.legado_cliente_id = v_row.id::text) then
            v_pulados := v_pulados + 1;
            continue;
        end if;

        v_migrados := v_migrados + 1;
        if p_dry_run then
            continue;
        end if;

        v_org_id := null;
        v_pessoa_id := null;
        v_digits := regexp_replace(coalesce(v_row.cpf_cnpj, ''), '\D', '', 'g');

        -- CNPJ (14 dígitos) → organização
        if length(v_digits) = 14 then
            select id into v_org_id from public.organizacoes
            where tenant_id is not distinct from v_row.tenant_id
              and regexp_replace(coalesce(cnpj,''), '\D', '', 'g') = v_digits
            limit 1;
            if v_org_id is null then
                insert into public.organizacoes (tenant_id, razao_social, nome_fantasia, cnpj)
                values (v_row.tenant_id, v_row.nome, v_row.nome, v_row.cpf_cnpj)
                returning id into v_org_id;
                v_orgs := v_orgs + 1;
            end if;
        end if;

        -- Sempre cria/reaproveita a pessoa de contato
        select id into v_pessoa_id from public.pessoas
        where tenant_id is not distinct from v_row.tenant_id
          and deleted_at is null
          and (
              (length(v_digits) = 11 and regexp_replace(coalesce(cpf,''), '\D', '', 'g') = v_digits)
              or (coalesce(v_row.telefone,'') <> '' and telefone = v_row.telefone)
              or (coalesce(v_row.email,'') <> '' and lower(email) = lower(v_row.email))
          )
        limit 1;

        if v_pessoa_id is null then
            insert into public.pessoas (tenant_id, organizacao_id, nome, email, telefone, ddi, cpf)
            values (
                v_row.tenant_id, v_org_id, v_row.nome, v_row.email, v_row.telefone,
                coalesce(v_row.ddi, '+55'),
                case when length(v_digits) = 11 then v_row.cpf_cnpj else null end
            )
            returning id into v_pessoa_id;
        end if;

        insert into public.negocios (
            tenant_id, organizacao_id, pessoa_contato_principal_id, titulo, valor,
            stage_id, status, temperatura, responsavel, responsavel_id,
            motivo_perda, dados_extras, legado_cliente_id, created_at
        ) values (
            v_row.tenant_id, v_org_id, v_pessoa_id,
            coalesce(v_row.nome, 'Negócio sem título'),
            coalesce(public.to_numeric_seguro(v_row.valor::text), public.to_numeric_seguro(v_row.conta_energia_media::text)),
            v_row.stage_id, v_row.status, v_row.temperatura, v_row.responsavel,
            null,
            v_row.motivo_perda,
            jsonb_strip_nulls(jsonb_build_object(
                'cep', v_row.cep,
                'endereco_instalacao', v_row.endereco_instalacao,
                'numero', v_row.numero,
                'complemento', v_row.complemento,
                'conta_energia_media', v_row.conta_energia_media
            )),
            v_row.id::text,
            coalesce(v_row.created_at, now())
        );

        insert into public.negocios_pessoas (tenant_id, negocio_id, pessoa_id, papel)
        select v_row.tenant_id, n.id, v_pessoa_id, 'decisor'
        from public.negocios n where n.legado_cliente_id = v_row.id::text
        on conflict (negocio_id, pessoa_id) do nothing;
    end loop;

    return query
        select case when p_dry_run then 'SERIAM migrados (dry-run)' else 'migrados' end::text, v_migrados
        union all select 'já migrados (pulados)'::text, v_pulados
        union all select 'organizações criadas'::text, v_orgs;
end;
$$;

-- ---------------------------------------------------------------------
-- VIEW DE COMPATIBILIDADE "clientes"
-- Se clientes ainda for tabela física: NÃO mexe (rodar a migração de dados
-- primeiro, depois: alter table clientes rename to clientes_legado; e rodar
-- este arquivo de novo).
-- Se clientes não existir ou já for view: (re)cria a view sobre negocios,
-- com triggers INSTEAD OF para INSERT/UPDATE/DELETE — o frontend atual
-- continua funcionando sem alteração nenhuma.
-- ---------------------------------------------------------------------
do $$
begin
    if exists (
        select 1 from information_schema.tables
        where table_schema = 'public' and table_name = 'clientes' and table_type = 'BASE TABLE'
    ) then
        raise notice 'Tabela física clientes ainda existe. Rode select * from migrar_clientes_para_negocios(false); depois renomeie: alter table public.clientes rename to clientes_legado; e execute este arquivo novamente para criar a view de compatibilidade.';
        return;
    end if;

    execute $view$
        create or replace view public.clientes as
        select
            n.id,
            n.tenant_id,
            coalesce(p.nome, o.nome_fantasia, o.razao_social, n.titulo) as nome,
            coalesce(p.cpf, o.cnpj) as cpf_cnpj,
            p.telefone,
            p.email,
            coalesce(p.ddi, '+55') as ddi,
            n.dados_extras->>'cep' as cep,
            n.dados_extras->>'endereco_instalacao' as endereco_instalacao,
            n.dados_extras->>'numero' as numero,
            n.dados_extras->>'complemento' as complemento,
            public.to_numeric_seguro(n.dados_extras->>'conta_energia_media') as conta_energia_media,
            n.valor,
            n.status,
            n.stage_id,
            n.temperatura,
            n.responsavel,
            n.responsavel_id,
            n.motivo_perda,
            n.fechado_em as data_fechamento,
            n.fechado_em,
            n.data_prevista_fechamento,
            n.organizacao_id,
            n.pessoa_contato_principal_id,
            n.pipeline_id,
            n.titulo,
            n.dados_extras,
            n.created_at,
            n.updated_at
        from public.negocios n
        left join public.pessoas p on p.id = n.pessoa_contato_principal_id
        left join public.organizacoes o on o.id = n.organizacao_id
        where n.deleted_at is null
    $view$;

    -- CRÍTICO: sem security_invoker a view roda com privilégio do dono e
    -- IGNORA a RLS de negocios/pessoas/organizacoes — vazaria dados entre
    -- tenants. Com security_invoker=on, a RLS do usuário logado é aplicada.
    execute 'alter view public.clientes set (security_invoker = on)';
end $$;

-- Triggers INSTEAD OF para a view (só se clientes for view)
create or replace function public.fn_clientes_view_insert()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    v_tenant uuid;
    v_pessoa_id uuid;
    v_org_id uuid;
    v_negocio_id uuid;
    v_digits text;
begin
    v_tenant := coalesce(new.tenant_id, public.current_tenant_id());
    if v_tenant is null then
        raise exception 'tenant_id não pôde ser resolvido para o insert em clientes.';
    end if;

    v_digits := regexp_replace(coalesce(new.cpf_cnpj, ''), '\D', '', 'g');

    if length(v_digits) = 14 then
        select id into v_org_id from public.organizacoes
        where tenant_id = v_tenant
          and regexp_replace(coalesce(cnpj,''), '\D', '', 'g') = v_digits
        limit 1;
        if v_org_id is null then
            insert into public.organizacoes (tenant_id, razao_social, nome_fantasia, cnpj)
            values (v_tenant, new.nome, new.nome, new.cpf_cnpj)
            returning id into v_org_id;
        end if;
    end if;

    -- Reaproveita pessoa por CPF/telefone/email dentro do tenant (anti-duplicata)
    select id into v_pessoa_id from public.pessoas
    where tenant_id = v_tenant
      and deleted_at is null
      and (
          (length(v_digits) = 11 and regexp_replace(coalesce(cpf,''), '\D', '', 'g') = v_digits)
          or (coalesce(new.telefone,'') <> '' and telefone = new.telefone)
          or (coalesce(new.email,'') <> '' and lower(email) = lower(new.email))
      )
    limit 1;

    if v_pessoa_id is null then
        insert into public.pessoas (tenant_id, organizacao_id, nome, email, telefone, ddi, cpf)
        values (
            v_tenant, v_org_id, new.nome, new.email, new.telefone,
            coalesce(new.ddi, '+55'),
            case when length(v_digits) = 11 then new.cpf_cnpj else null end
        )
        returning id into v_pessoa_id;
    end if;

    insert into public.negocios (
        tenant_id, organizacao_id, pessoa_contato_principal_id, titulo, valor,
        stage_id, pipeline_id, status, temperatura, responsavel, responsavel_id, motivo_perda,
        fechado_em, dados_extras
    ) values (
        v_tenant, v_org_id, v_pessoa_id,
        coalesce(new.titulo, new.nome, 'Negócio sem título'),
        coalesce(new.valor, new.conta_energia_media),
        new.stage_id, new.pipeline_id, new.status, new.temperatura,
        new.responsavel, new.responsavel_id, new.motivo_perda,
        new.data_fechamento,
        jsonb_strip_nulls(coalesce(new.dados_extras, '{}'::jsonb) || jsonb_build_object(
            'cep', new.cep,
            'endereco_instalacao', new.endereco_instalacao,
            'numero', new.numero,
            'complemento', new.complemento,
            'conta_energia_media', new.conta_energia_media
        ))
    )
    returning id into v_negocio_id;

    insert into public.negocios_pessoas (tenant_id, negocio_id, pessoa_id, papel)
    values (v_tenant, v_negocio_id, v_pessoa_id, 'decisor')
    on conflict (negocio_id, pessoa_id) do nothing;

    new.id := v_negocio_id;
    new.tenant_id := v_tenant;
    return new;
end;
$$;

create or replace function public.fn_clientes_view_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    v_pessoa_id uuid;
    v_tenant uuid;
    v_compartilhada bigint;
    v_nova_pessoa uuid;
begin
    select pessoa_contato_principal_id, tenant_id into v_pessoa_id, v_tenant
    from public.negocios where id = old.id;

    -- Defesa em profundidade: esta função é SECURITY DEFINER e ignora a RLS.
    -- A view já filtra por tenant (security_invoker), mas a checagem explícita
    -- garante que nenhum caminho futuro permita editar negócio de outro tenant.
    if v_tenant is null or not public.tenant_filter(v_tenant) then
        raise exception 'Registro fora do seu tenant.' using errcode = '42501';
    end if;

    -- FORK-ON-WRITE: a mesma pessoa pode estar em vários negócios (é o
    -- comportamento correto em B2B). Mas a tela antiga edita "o cliente"
    -- como se fosse exclusivo do lead — sem esta cópia, renomear um lead
    -- renomearia silenciosamente os outros negócios do mesmo contato.
    if v_pessoa_id is not null then
        select count(*) into v_compartilhada
        from public.negocios
        where pessoa_contato_principal_id = v_pessoa_id
          and deleted_at is null;

        if v_compartilhada > 1 then
            insert into public.pessoas (tenant_id, organizacao_id, nome, email, telefone, ddi, cpf, cargo, dados_extras)
            select tenant_id, organizacao_id,
                   coalesce(new.nome, nome), new.email, new.telefone,
                   coalesce(new.ddi, ddi),
                   case when length(regexp_replace(coalesce(new.cpf_cnpj,''), '\D', '', 'g')) = 11
                        then new.cpf_cnpj else cpf end,
                   cargo, dados_extras
            from public.pessoas where id = v_pessoa_id
            returning id into v_nova_pessoa;

            update public.negocios set pessoa_contato_principal_id = v_nova_pessoa where id = old.id;

            update public.negocios_pessoas
            set pessoa_id = v_nova_pessoa
            where negocio_id = old.id and pessoa_id = v_pessoa_id;

            v_pessoa_id := null;  -- já gravado na cópia
        end if;
    end if;

    -- Campos de pessoa
    if v_pessoa_id is not null then
        update public.pessoas set
            nome = coalesce(new.nome, nome),
            email = new.email,
            telefone = new.telefone,
            ddi = coalesce(new.ddi, ddi),
            cpf = case
                when length(regexp_replace(coalesce(new.cpf_cnpj,''), '\D', '', 'g')) = 11 then new.cpf_cnpj
                else cpf
            end
        where id = v_pessoa_id;
    end if;

    -- Campos de negócio
    update public.negocios set
        titulo = coalesce(new.titulo, new.nome, titulo),
        valor = coalesce(new.valor, valor),
        stage_id = new.stage_id,
        pipeline_id = coalesce(new.pipeline_id, pipeline_id),
        status = new.status,
        temperatura = new.temperatura,
        responsavel = new.responsavel,
        responsavel_id = coalesce(new.responsavel_id, responsavel_id),
        motivo_perda = new.motivo_perda,
        -- O frontend manda data_fechamento ao mover o card; quando não manda,
        -- a etapa terminal (ganho/perdido) define o fechamento automaticamente.
        fechado_em = case
            when new.data_fechamento is not null then new.data_fechamento
            when exists (
                select 1 from public.pipeline_stages ps
                where ps.id = new.stage_id and (ps.ganho or ps.perdido)
            ) and fechado_em is null then now()
            when exists (
                select 1 from public.pipeline_stages ps
                where ps.id = new.stage_id and not ps.ganho and not ps.perdido
            ) then null
            else fechado_em
        end,
        -- Preserva o que já existe, aplica os campos customizados que o
        -- cliente enviou (new.dados_extras) e por último os campos fixos do
        -- formulário legado. Sem o new.dados_extras aqui, todo valor de campo
        -- customizado editado pela tela era descartado em silêncio.
        dados_extras = jsonb_strip_nulls(
            coalesce(dados_extras, '{}'::jsonb)
            || coalesce(new.dados_extras, '{}'::jsonb)
            || jsonb_build_object(
                'cep', new.cep,
                'endereco_instalacao', new.endereco_instalacao,
                'numero', new.numero,
                'complemento', new.complemento,
                'conta_energia_media', new.conta_energia_media
            )
        )
    where id = old.id;

    return new;
end;
$$;

create or replace function public.fn_clientes_view_delete()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    v_tenant uuid;
begin
    select tenant_id into v_tenant from public.negocios where id = old.id;

    if v_tenant is null or not public.tenant_filter(v_tenant) then
        raise exception 'Registro fora do seu tenant.' using errcode = '42501';
    end if;

    -- Soft delete: nunca perde dado por engano do usuário
    update public.negocios set deleted_at = now() where id = old.id;
    return old;
end;
$$;

do $$
begin
    if exists (
        select 1 from information_schema.views
        where table_schema = 'public' and table_name = 'clientes'
    ) then
        execute 'drop trigger if exists clientes_view_insert on public.clientes';
        execute 'create trigger clientes_view_insert instead of insert on public.clientes for each row execute function public.fn_clientes_view_insert()';
        execute 'drop trigger if exists clientes_view_update on public.clientes';
        execute 'create trigger clientes_view_update instead of update on public.clientes for each row execute function public.fn_clientes_view_update()';
        execute 'drop trigger if exists clientes_view_delete on public.clientes';
        execute 'create trigger clientes_view_delete instead of delete on public.clientes for each row execute function public.fn_clientes_view_delete()';
    end if;
end $$;

-- Realtime: eventos passam a nascer em negocios (a view não emite eventos)
do $$
begin
    if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
        begin
            alter publication supabase_realtime add table public.negocios;
        exception when duplicate_object then
            null;
        when others then
            raise notice 'Não foi possível adicionar negocios à publication realtime: %', sqlerrm;
        end;
    end if;
end $$;
