-- =====================================================================
-- CRM POLATTO — MIGRATION 07: MONITORAMENTO DE ERROS EM PRODUÇÃO
--
-- Item da seção 5 do escopo. Sem dependência de serviço externo:
-- o frontend registra erros de runtime aqui via RPC registrar_erro_cliente
-- (window.onerror / unhandledrejection / ErrorBoundary — ver
-- src/utility/errorMonitoring.ts). Consultar erros recentes:
--   select * from public.client_errors order by criado_em desc limit 50;
--
-- IDEMPOTENTE. Executar após 02.
-- =====================================================================

create table if not exists public.client_errors (
    id bigint generated by default as identity primary key,
    tenant_id uuid,
    user_id uuid,
    email_usuario text,
    mensagem text not null,
    stack text,
    url text,
    user_agent text,
    origem text default 'window.onerror',   -- window.onerror | unhandledrejection | error-boundary | manual
    contexto jsonb not null default '{}'::jsonb,
    criado_em timestamptz not null default now()
);

create index if not exists idx_client_errors_data on public.client_errors (criado_em desc);
create index if not exists idx_client_errors_tenant on public.client_errors (tenant_id, criado_em desc);

alter table public.client_errors enable row level security;
drop policy if exists client_errors_leitura_admin on public.client_errors;
create policy client_errors_leitura_admin on public.client_errors
    for select to authenticated
    using (public.is_system_admin() or public.tenant_filter(tenant_id));
-- Escrita apenas via RPC (security definer + rate limit). Sem policy de insert.

create or replace function public.registrar_erro_cliente(
    p_mensagem text,
    p_stack text default null,
    p_url text default null,
    p_user_agent text default null,
    p_origem text default 'manual',
    p_contexto jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    -- Protege contra flood: 60 erros/usuário/hora é suficiente para diagnóstico
    begin
        perform public.enforce_rate_limit('registrar_erro_cliente', 60, interval '1 hour');
    exception when others then
        return; -- estourou o limite: descarta silenciosamente
    end;

    insert into public.client_errors (tenant_id, user_id, email_usuario, mensagem, stack, url, user_agent, origem, contexto)
    values (
        public.current_tenant_id(),
        auth.uid(),
        coalesce(auth.jwt() ->> 'email', 'anon'),
        left(coalesce(p_mensagem, 'erro sem mensagem'), 2000),
        left(p_stack, 8000),
        left(p_url, 1000),
        left(p_user_agent, 500),
        left(coalesce(p_origem, 'manual'), 50),
        coalesce(p_contexto, '{}'::jsonb)
    );
exception when others then
    null; -- monitoramento nunca pode quebrar a aplicação
end;
$$;

-- Retenção: erros somem depois de 90 dias (chamar junto da política de retenção)
create or replace function public.limpar_erros_antigos()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_count bigint;
begin
    delete from public.client_errors where criado_em < now() - interval '90 days';
    get diagnostics v_count = row_count;
    return v_count;
end;
$$;
