-- =====================================================================
-- CRM POLATTO — MIGRATION 00: TABELAS BASE
--
-- PRIMEIRA a rodar. Cria o esqueleto que todas as demais migrations
-- assumem existir: empresas, vínculo de usuários, clientes (modelo
-- legado), funil, equipe, agenda, timeline, documentos e metas.
--
-- Por que existe: as migrations 01..09 partiam do princípio de que essas
-- tabelas já estavam no banco (o que é verdade na instalação atual, criada
-- à mão). Em um projeto Supabase NOVO — cliente novo, ambiente de staging,
-- recuperação de backup — nada disso existia e a sequência não subia.
--
-- IDEMPOTENTE: em bancos que já têm as tabelas, apenas garante colunas
-- faltantes e não toca em dado algum.
-- =====================================================================

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------
-- EMPRESAS — os tenants
-- ---------------------------------------------------------------------
create table if not exists public.empresas (
    id uuid primary key default gen_random_uuid(),
    nome text not null,
    segmento text default 'energia_solar',
    created_at timestamptz not null default now()
);

alter table public.empresas add column if not exists nome text;
alter table public.empresas add column if not exists segmento text default 'energia_solar';
alter table public.empresas add column if not exists created_at timestamptz default now();

-- ---------------------------------------------------------------------
-- UTILIZADORES_EMPRESAS — vínculo usuário ↔ empresa.
-- É a base de current_tenant_id(): sem esta tabela, todo o isolamento
-- multi-tenant fica fail-closed e ninguém acessa nada.
-- ---------------------------------------------------------------------
create table if not exists public.utilizadores_empresas (
    id uuid primary key default gen_random_uuid(),
    auth_uid uuid,
    empresa_id uuid,
    role text,
    created_at timestamptz not null default now()
);

alter table public.utilizadores_empresas add column if not exists auth_uid uuid;
alter table public.utilizadores_empresas add column if not exists empresa_id uuid;
alter table public.utilizadores_empresas add column if not exists role text;
alter table public.utilizadores_empresas add column if not exists created_at timestamptz default now();

create index if not exists idx_utilizadores_empresas_auth on public.utilizadores_empresas (auth_uid);

-- ---------------------------------------------------------------------
-- SYSTEM_ADMINS — superadmin da plataforma (fonte de verdade única)
-- ---------------------------------------------------------------------
create table if not exists public.system_admins (
    id uuid primary key default gen_random_uuid(),
    email text unique not null,
    created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- CLIENTES — modelo legado. A migration 01 transforma isto na view de
-- compatibilidade sobre negocios; aqui ele nasce como tabela para que a
-- sequência de virada funcione igual em banco novo e em produção.
-- ---------------------------------------------------------------------
create table if not exists public.clientes (
    id bigint generated by default as identity primary key,
    tenant_id uuid,
    nome text,
    cpf_cnpj text,
    telefone text,
    email text,
    ddi text default '+55',
    cep text,
    endereco_instalacao text,
    numero text,
    complemento text,
    conta_energia_media numeric,
    valor numeric,
    status text,
    stage_id bigint,
    temperatura text,
    responsavel text,
    responsavel_id uuid,
    motivo_perda text,
    data_fechamento timestamptz,
    created_at timestamptz default now()
);

do $$
declare
    v_coluna text;
begin
    -- Só faz sentido enquanto clientes for TABELA (depois da virada é view)
    if exists (
        select 1 from information_schema.tables
        where table_schema = 'public' and table_name = 'clientes' and table_type = 'BASE TABLE'
    ) then
        foreach v_coluna in array array[
            'tenant_id uuid', 'nome text', 'cpf_cnpj text', 'telefone text', 'email text',
            'ddi text', 'cep text', 'endereco_instalacao text', 'numero text',
            'complemento text', 'conta_energia_media numeric', 'valor numeric',
            'status text', 'temperatura text', 'responsavel text', 'responsavel_id uuid',
            'motivo_perda text', 'data_fechamento timestamptz', 'created_at timestamptz'
        ] loop
            execute format('alter table public.clientes add column if not exists %s', v_coluna);
        end loop;
    end if;
end $$;

-- ---------------------------------------------------------------------
-- PIPELINE_STAGES — etapas do funil (a 01 acrescenta pipeline_id etc.)
-- ---------------------------------------------------------------------
create table if not exists public.pipeline_stages (
    id bigint generated by default as identity primary key,
    tenant_id uuid,
    nome text,
    cor text,
    ordem integer default 0
);

-- ---------------------------------------------------------------------
-- FUNCIONARIOS — equipe comercial
-- ---------------------------------------------------------------------
create table if not exists public.funcionarios (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid,
    user_id uuid,
    nome text not null,
    email text unique not null,
    cargo text,
    ativo boolean default true,
    deleted_at timestamptz,
    created_at timestamptz not null default now()
);

alter table public.funcionarios add column if not exists tenant_id uuid;
alter table public.funcionarios add column if not exists user_id uuid;
alter table public.funcionarios add column if not exists cargo text;
alter table public.funcionarios add column if not exists ativo boolean default true;
alter table public.funcionarios add column if not exists deleted_at timestamptz;

-- ---------------------------------------------------------------------
-- TAREFAS — agenda do vendedor
-- ---------------------------------------------------------------------
create table if not exists public.tarefas (
    id bigint generated by default as identity primary key,
    tenant_id uuid,
    titulo text not null,
    descricao text,
    data_vencimento timestamptz,
    concluido boolean default false,
    tipo text default 'visita',
    cliente_id text,
    responsavel text,
    execucao_status text,
    deleted_at timestamptz,
    created_at timestamptz not null default now()
);

alter table public.tarefas add column if not exists tenant_id uuid;
alter table public.tarefas add column if not exists descricao text;
alter table public.tarefas add column if not exists data_vencimento timestamptz;
alter table public.tarefas add column if not exists concluido boolean default false;
alter table public.tarefas add column if not exists tipo text default 'visita';
alter table public.tarefas add column if not exists cliente_id text;
alter table public.tarefas add column if not exists responsavel text;
alter table public.tarefas add column if not exists execucao_status text;
alter table public.tarefas add column if not exists deleted_at timestamptz;

-- ---------------------------------------------------------------------
-- ATIVIDADES_LEAD — timeline. As colunas duplicadas (tipo/activity_type,
-- titulo/title, criado_por/author) refletem variações que a tabela
-- acumulou em produção; o código lida com ambas.
-- ---------------------------------------------------------------------
create table if not exists public.atividades_lead (
    id bigint generated by default as identity primary key,
    tenant_id uuid,
    cliente_id text,
    lead_id text,
    funcionario_id uuid,
    tipo text,
    tipo_atividade text,
    activity_type text,
    titulo text,
    title text,
    descricao text,
    notes text,
    criado_por text,
    author text,
    de_status text,
    from_status text,
    para_status text,
    to_status text,
    arquivo_nome text,
    file_name text,
    arquivo_path text,
    file_path text,
    arquivo_url text,
    file_url text,
    data_atividade timestamptz,
    metadados jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- DOCUMENTOS_LEAD — anexos versionados (o arquivo vive no Storage)
-- ---------------------------------------------------------------------
create table if not exists public.documentos_lead (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid,
    cliente_id text,
    tipo text,
    nome_arquivo text,
    caminho_storage text,
    tamanho_bytes bigint,
    versao integer default 1,
    status text default 'ativo',
    enviado_por text,
    deleted_at timestamptz,
    created_at timestamptz not null default now()
);

alter table public.documentos_lead add column if not exists tenant_id uuid;
alter table public.documentos_lead add column if not exists deleted_at timestamptz;

-- ---------------------------------------------------------------------
-- CLIENTE_STATUS_HISTORY — auditoria de movimentação no funil
-- ---------------------------------------------------------------------
create table if not exists public.cliente_status_history (
    id bigint generated by default as identity primary key,
    tenant_id uuid,
    cliente_id bigint,
    de_status text,
    para_status text,
    movido_em timestamptz not null default now(),
    movido_por text
);

alter table public.cliente_status_history add column if not exists tenant_id uuid;

create index if not exists idx_cliente_status_history_movido_em
    on public.cliente_status_history (movido_em desc);

-- ---------------------------------------------------------------------
-- METAS — objetivos por funcionário
-- ---------------------------------------------------------------------
create table if not exists public.metas (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid,
    funcionario_id uuid,
    valor_meta numeric(14, 2) not null default 0,
    mes_referencia date not null default date_trunc('month', now())::date,
    created_at timestamptz not null default now()
);

alter table public.metas add column if not exists tenant_id uuid;

-- ---------------------------------------------------------------------
-- GRANTS — sem isto o PostgREST responde "permission denied" mesmo com a
-- RLS correta. A segurança continua sendo a RLS, não o grant.
-- ---------------------------------------------------------------------
do $$
declare
    v_tabela text;
begin
    foreach v_tabela in array array[
        'empresas', 'utilizadores_empresas', 'clientes', 'pipeline_stages',
        'funcionarios', 'tarefas', 'atividades_lead', 'documentos_lead',
        'cliente_status_history', 'metas'
    ] loop
        if to_regclass('public.' || v_tabela) is not null then
            execute format(
                'grant select, insert, update, delete on public.%I to authenticated',
                v_tabela
            );
        end if;
    end loop;
    execute 'grant usage on all sequences in schema public to authenticated';
exception when insufficient_privilege then
    raise notice 'Sem permissão para GRANT — conferir acesso do role authenticated.';
end $$;

-- Meta de QUANTIDADE de vendas, ao lado da meta de valor. A tela de Metas
-- grava e lê esta coluna; sem ela, "Salvar quotas" falhava no PostgREST.
alter table public.metas add column if not exists target_wins integer not null default 0;
