-- =====================================================================
-- HARNESS DE TESTE — simula o ambiente Supabase em um Postgres local
--
-- Recria o mínimo que as migrations assumem existir em produção:
--   - schema auth com uid()/jwt() lendo request.jwt.claims (igual PostgREST)
--   - schema storage com objects e foldername()
--   - roles anon/authenticated/service_role
--   - tabelas legadas do CRM antes da migração (clientes, utilizadores_empresas,
--     funcionarios, tarefas, atividades_lead, documentos_lead, ...)
--
-- Uso: psql -f database/tests/00_harness_supabase.sql
-- Não faz parte do deploy — é apenas o ambiente de teste local.
-- =====================================================================

create extension if not exists pgcrypto;
create extension if not exists pg_trgm;

do $$
begin
    if not exists (select 1 from pg_roles where rolname = 'anon') then
        create role anon nologin;
    end if;
    if not exists (select 1 from pg_roles where rolname = 'authenticated') then
        create role authenticated nologin;
    end if;
    if not exists (select 1 from pg_roles where rolname = 'service_role') then
        create role service_role nologin bypassrls;
    end if;
end $$;

create schema if not exists auth;
create schema if not exists storage;

-- auth.uid()/auth.jwt() com a mesma semântica do Supabase
create or replace function auth.jwt()
returns jsonb
language sql
stable
as $$
    select coalesce(
        nullif(current_setting('request.jwt.claims', true), ''),
        '{}'
    )::jsonb;
$$;

create or replace function auth.uid()
returns uuid
language sql
stable
as $$
    select nullif(auth.jwt() ->> 'sub', '')::uuid;
$$;

create table if not exists auth.users (
    id uuid primary key default gen_random_uuid(),
    email text unique
);

-- storage.objects + foldername (split do path em segmentos)
create table if not exists storage.objects (
    id uuid primary key default gen_random_uuid(),
    bucket_id text,
    name text,
    owner uuid,
    created_at timestamptz default now()
);

create or replace function storage.foldername(name text)
returns text[]
language plpgsql
immutable
as $$
declare
    parts text[];
begin
    parts := string_to_array(name, '/');
    return parts[1:array_length(parts, 1) - 1];
end;
$$;

alter table storage.objects enable row level security;

grant usage on schema public, auth, storage to anon, authenticated, service_role;
grant all on all tables in schema public to anon, authenticated, service_role;
grant all on all tables in schema storage to anon, authenticated, service_role;

-- O Supabase configura default privileges para que TABELAS NOVAS já nasçam
-- acessíveis aos roles da API. Sem isso, tudo que a migration cria fica
-- inacessível ao frontend (erro "permission denied for table").
alter default privileges in schema public
    grant all on tables to anon, authenticated, service_role;
alter default privileges in schema public
    grant all on sequences to anon, authenticated, service_role;

-- ---------------------------------------------------------------------
-- TABELAS LEGADAS (estado do banco ANTES das migrations)
-- ---------------------------------------------------------------------
create table if not exists public.empresas (
    id uuid primary key default gen_random_uuid(),
    nome text not null,
    segmento text default 'energia_solar',
    created_at timestamptz not null default now()
);

create table if not exists public.utilizadores_empresas (
    id uuid primary key default gen_random_uuid(),
    auth_uid uuid,
    empresa_id uuid,
    role text
);

create table if not exists public.system_admins (
    id uuid primary key default gen_random_uuid(),
    email text unique not null,
    created_at timestamptz not null default now()
);

create table if not exists public.clientes (
    id bigint generated by default as identity primary key,
    tenant_id uuid,
    nome text,
    cpf_cnpj text,
    telefone text,
    email text,
    ddi text default '+55',
    cep text,
    endereco_instalacao text,
    numero text,
    complemento text,
    conta_energia_media numeric,
    valor numeric,
    status text,
    stage_id bigint,
    temperatura text,
    responsavel text,
    motivo_perda text,
    created_at timestamptz default now()
);

create table if not exists public.pipeline_stages (
    id bigint generated by default as identity primary key,
    nome text,
    cor text,
    ordem integer default 0
);

create table if not exists public.funcionarios (
    id uuid default gen_random_uuid() primary key,
    user_id uuid,
    nome text not null,
    email text unique not null,
    cargo text,
    ativo boolean default true,
    created_at timestamptz default now() not null
);

create table if not exists public.tarefas (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    titulo text not null,
    descricao text,
    data_vencimento timestamptz,
    concluido boolean default false,
    tipo text default 'visita',
    cliente_id text,
    responsavel text
);

create table if not exists public.atividades_lead (
    id bigint generated by default as identity primary key,
    cliente_id text,
    tenant_id uuid,
    activity_type text,
    tipo text,
    titulo text,
    descricao text,
    criado_por text,
    de_status text,
    para_status text,
    data_atividade timestamptz,
    created_at timestamptz default now()
);

create table if not exists public.documentos_lead (
    id uuid primary key default gen_random_uuid(),
    tenant_id uuid,
    cliente_id text,
    tipo text,
    nome_arquivo text,
    caminho_storage text,
    tamanho_bytes bigint,
    versao integer default 1,
    status text default 'ativo',
    enviado_por text,
    created_at timestamptz default now(),
    deleted_at timestamptz
);

create table if not exists public.cliente_status_history (
    id bigint generated by default as identity primary key,
    cliente_id bigint,
    de_status text,
    para_status text,
    movido_em timestamptz not null default now(),
    movido_por text
);

create table if not exists public.metas (
    id uuid default gen_random_uuid() primary key,
    funcionario_id uuid,
    valor_meta numeric(10,2) not null default 0,
    mes_referencia date not null default date_trunc('month', now())::date,
    created_at timestamptz default now() not null
);
